### ISSUE TITLE
Chaning userChrome.css Navigation bar width value causes issues

### ISSUE THREAD

**Issue by Luiderd** [Doosty/Oneliner-Deluxe#2]
I used this theme because it is really good, however when changing the values inside of the userChrome.css - /* Navigation bar width, what remains is taken up by the tab bar */ 
Firefox always breaks. It was the only value that I had modified (20vw -> 18wv) and when I restarted Firefox, the bookmark bar would not display any bookmarks or autohide. Webpages would not display at all and it was unusable. 
Also I needed to shorten the actual URL bar to make it smaller as well so I used this code

#urlbar-container{
  max-width: 400px !important;
  min-width: 400px !important;
}
This code and changing the values causes the problems but I do not know why
An important remark is that I fixed this my DELETING the userChrome.css file in my Firefox profile folder and restarting Firefox. REPLACING it with a brand new file from github did not fix the problem. I have recreated this problem several times.

**Comment by Doosty** [comment]
I tested that value with any number from 0-100, plus i also see you have a typo in your post "20vw -> 18wv". If you broke your profile you can try to troubleshoot mode with `about:support` and clearing cache. I hope its just a typo but i will look into it, and i also plan to release a few improvements in the next day, the navbar width being one of them.

**Comment by Luiderd** [comment]
Yes fixing the typo was part of it, but the bookmark bar stopped auto hiding. The code might be conflicting with the other parts.

**Comment by Luiderd** [comment]
> 
> 
> Yes fixing the typo was part of it, but the bookmark bar stopped auto hiding. The code might be conflicting with the other parts.

Deleting the extra code that I added also does not fix it even though it is what caused it. The way that I temporarily fixed this is by toggling Firefox in safe mode on and off. I have disabled all extensions and the issue still persists when changing the value. Clearing startup cache does not fix it either.

**Comment by Doosty** [comment]
The only time i bricked a profile like that was when i put nav & control buttons inside Customize view and restarted. Not sure what you did to userchrome to brick it in that way. Anyway i pushed an update that has an extra value dealing with nav width, maybe it helps with what you want. This time i suggest you experiment with a new tester profile beforehand. Going to sleep now, good luck.

**Comment by Luiderd** [comment]
> 
> 
> The only time i bricked a profile like that was when i put nav & control buttons inside Customize view and restarted. Not sure what you did to userchrome to brick it in that way. Anyway i pushed an update that has an extra value dealing with nav width, maybe it helps with what you want. This time i suggest you experiment with a new tester profile beforehand. Going to sleep now, good luck.

This new value solved my problem! Thank you so much!
